# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ghw-server-example

on:
  push:
    branches:
      - ghw-azure
        # Only trigger if changes are made to these files or directories
    paths:
      - .github/workflows/azure-web-app-backend-pipeline.yml
      - "app/server/**"

      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # gives github actions context/code in the repo in the specified branch.

      - name: Set up Node.js version # Do evrything we do locally
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
        working-directory: app/server

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: app/server


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app/server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B6CDE86220884E58BDD8A3D12FEE5B24 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CFD687C4021C40D2AD7939800D3096B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0F4D1D2E1D94AE09299523A5B5F0B3A }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ghw-server-example"
          slot-name: "Production"
          package: .
